### ISSUE TITLE
The number of papers published does not match

### ISSUE THREAD

**Issue by GRF-Sunomikp31** [hszhoushen/Target-Robotics-and-Visions-Journal-Conference#1]
Hi, I noticed that the number of papers on the document is not in line, or because it is not the latest statistics, for example, TRO2022 recorded 230+ papers, IJRR2022 included 40+ papers, maybe you should mark your year statistical year~
best，
Dong Li

**Comment by hszhoushen** [comment]
> Hi, I noticed that the number of papers on the document is not in line, or because it is not the latest statistics, for example, TRO2022 recorded 230+ papers, IJRR2022 included 40+ papers, maybe you should mark your year statistical year~ best， Dong Li

Dong, thank you for your information. After carefully checking the source from dblp, TRO [1] has published 235 papers and IJRR [2] has published 49 papers in 2022, according to dblp library.

[1] https://dblp.org/db/journals/trob/trob38.html
[2] https://dblp.org/db/journals/ijrr/ijrr41.html

**Comment by GRF-Sunomikp31** [comment]
I mean you can check the others as well.
